services:
  app:
    container_name: studiu_next
    build:
      context: .
    image: nextjs-prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      prisma-migrator:
        condition: service_completed_successfully
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
    networks:
      - localnet
    volumes:
      - ${UPLOADS:-./uploads}:/app/storage
  postgres:
    container_name: studiu_postgres
    image: postgres:15
    env_file:
      - .env
    networks:
      - localnet
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  prisma-migrator:
    container_name: studiu_migrator
    build:
      context: .
      target: builder
    command: bunx prisma migrate deploy
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
    networks:
      - localnet
    depends_on:
      postgres:
        condition: service_healthy

networks:
  localnet:
    driver: bridge

volumes:
  postgres_data:
